# theme.toml template for a Hugo theme

name = "Papillon"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "This theme is used for Ab&Durch, a german group of hobby actors."
homepage = "http://ab-und-durch.de/"
tags = ["", ""]
features = ["", ""]
min_version = 0.1.0

[author]
  name = "Leonard Siebeneicher"
  homepage = "leonard7e.ovh"

